### ISSUE TITLE
zipfile error in `train.py`

### ISSUE THREAD

**Issue by jayabrata97** [MCZhi/DIPP#12]
Hi, I am getting the `zipfile.BadZipFile: Bad CRC-32 for file 'map_crosswalks.npy'` while training. Has anyone else gotten this error? @MCZhi, do you have any idea?

**Comment by MCZhi** [comment]
I am not sure what's the problem. What OS are you using? And you may try updating the NumPy package.

**Comment by jayabrata97** [comment]
Hi @MCZhi, I am using Ubuntu 20.04. Can you please tell me what version of NumPy you have used? I installed all the packages from the YAML file given.

**Comment by MCZhi** [comment]
I am using the NumPy in the .yaml file. But I guess the error is in saving the .npy data though I don't know the exact reason, so I suggest installing a different NumPy version to see if the problem still exists.
