### ISSUE TITLE
Consult the data preprocessing problems

### ISSUE THREAD

**Issue by TimHo0331** [MCZhi/DIPP#13]
Dear authors,
    Very thankful for providing the code! A very interesting work!
    May I ask a question about data preprocessing of the map?
    Does the map_api in data_utils.py and data_proprocess.py refer to some other materials? (e.g. find the route, depth first search, generate target course,...) This part is kind of difficult to understand. And I want to ask if you could refer to some materials to help me know how to preprocess the lane graph? 
  Thank you so much!

**Comment by MCZhi** [comment]
Hi, @panda2020-sky, thank you for your interest. Part of the code is borrowed from [argoverse map_api](https://github.com/argoai/argoverse-api/blob/master/argoverse/map_representation/map_api.py) (e.g., dfs) and [python robotics](https://github.com/AtsushiSakai/PythonRobotics/tree/master/PathPlanning/FrenetOptimalTrajectory) (e.g., generate target course). You may check their code to know the details.
