### ISSUE TITLE
Some questions in my experiment

### ISSUE THREAD

**Issue by Ryansanity** [MCZhi/DIPP#16]
Hi authors, thank you for your open-source code, and i got some questions when i tried to reproduce the effect in the paper.
Premise is i preprocessed all raw data in /orig/scenario/training_20s and randomly selected 200000 as the training dataset and 24000 as the val dataset.Other parameters are consistent with the original paper.
QUESTIONS：
1、planner optimizer parameters:if we set max_iterations=50 step_size=0.2 in open loop test, while we set max_iterations=2, step_size=0.2 in training, we got a worse metrics than the result if we set  max_iterations=2, step_size=0.2 in open loop test
2、open loop test metrics: We found that some indicators were extraordinarily poor：
![image](https://user-images.githubusercontent.com/33254134/200210743-6b035fa2-a981-4c1f-953a-736da4869dff.png)
so we tried to change the plan cost weight to[1,10,10,1,1,30,100,10,10], we got the result like that:
![image](https://user-images.githubusercontent.com/33254134/200211254-cd5e496e-5d1a-478a-90ef-17e7a3a05f7e.png)
It seems that there is still a gap with the indicators in the paper.
3、open loop test Visualization results：

https://user-images.githubusercontent.com/33254134/200211901-b9c59f5a-a462-4d22-8d95-cc38574cbfd2.mp4

https://user-images.githubusercontent.com/33254134/200211952-4c6238c0-86ac-4c3e-b29f-2ba434ed804e.mp4

https://user-images.githubusercontent.com/33254134/200212218-6143c223-2772-4555-9abf-f114c14871b2.mp4
It seems that the visual effect is general, especially when turning.

**Comment by Ryansanity** [comment]
by the way, the above open loop test matrics we obtained in the case of max_iterations=2, step_size=0.2.

**Comment by MCZhi** [comment]
Hi, thank you for your interest in our work. Here are my answers to your questions and some suggestions.

1. I am not sure what kind of metrics you are referring to, but I think that using a smaller number of iterations could lead to better ADE or FDE if the initialization is already close to the ground truth. Even using the initial trajectory can give you better metrics in terms of position error but other metrics could be worse.
2. The poor acceleration and jerk metrics may be because you are using fewer iterations and using your manually designed cost function may not deliver the expected results, especially in closeness to humans. I would suggest still using the learned cost function.
3. The video files seem broken and unable to watch. It would be helpful for me to analyze your questions if you could provide functioning files.

Please feel free to let me if you have any further questions.

**Comment by Ryansanity** [comment]
> Hi, thank you for your interest in our work. Here are my answers to your questions and some suggestions.
> 
> 1. I am not sure what kind of metrics you are referring to, but I think that using a smaller number of iterations could lead to better ADE or FDE if the initialization is already close to the ground truth. Even using the initial trajectory can give you better metrics in terms of position error but other metrics could be worse.
> 2. The poor acceleration and jerk metrics may be because you are using fewer iterations and using your manually designed cost function may not deliver the expected results, especially in closeness to humans. I would suggest still using the learned cost function.
> 3. The video files seem broken and unable to watch. It would be helpful for me to analyze your questions if you could provide functioning files.
> 
> Please feel free to let me if you have any further questions.

Thank you for your reply！

1. we used 5 pretrained epoch and totally 20 epoch just as you provide in open source code. And if we use max_iterations=50 step_size=0.2,we got worse result almost in every matrics of open loop test.
2. we just change the self.register_buffer('scale', torch.tensor([...])) in predictor.py, they are still Learnable.
3. 

https://user-images.githubusercontent.com/33254134/200561083-62f4bab9-2ed1-4fa1-bf46-e0f8bfec789d.mp4

https://user-images.githubusercontent.com/33254134/200560762-e3b4636c-ca92-4e5c-97ac-2b495569d67e.mp4

https://user-images.githubusercontent.com/33254134/200561018-00b24465-b289-4a0b-94ed-fd758227966d.mp4

sorry about the broken vedios~
The above three are open-loop test videos, and AV seems to be out of control in the closed-loop test.
So, we are wondering if you can share your choosen dataset, to help us to reproduce the effect in the paper.
We look forward to your reply

**Comment by MCZhi** [comment]
Sorry for the late reply. I guess the possible reason is that the motion planner is not properly learned, could be the cost function or initialization. The chosen dataset I think is not an issue here, and you may refer to #5 for some information.
