### ISSUE TITLE
module 'torch.utils.cpp_extension' has no attribute 'CUDA_GCC_VERSIONS'

### ISSUE THREAD

**Issue by EcustBoy** [MCZhi/DIPP#17]
Hi author~ I follow your installation step, I use conda and finish "Install dependency" and  "Create conda env" steps,  (but I install python3.8 + torch 1.9 + cu111 because my machine **supports the highest cuda version is 11.1**, and is also equipped with cuda 11.1 by running "nvcc -V" ). 
But in "Install Theseus" step, I follow the installation steps as in official tutorial (https://github.com/facebookresearch/theseus)，
and **build from source**:

![image](https://user-images.githubusercontent.com/32817744/203899734-b715505e-d6d7-4da1-849a-69651607204b.png)

but the following error occurs:
![image](https://user-images.githubusercontent.com/32817744/203893920-a790f107-c1e7-43be-8bb6-ea264655f818.png)
it seems like pytorch version is not right? So I upgrade to torch 1.11 + cu111，but the same error is still reported.

I wonderif you've ever encountered the same error and can you give some advice？ I'll thanks for your reply~

**Comment by MCZhi** [comment]
Hi, @EcustBoy, sorry I don't know what caused this error. The Theseus library is still under frequent updates, so maybe you can try a previous version (eg 0.1.0 or 0.1.1) or try installing using pip.

**Comment by EcustBoy** [comment]
感谢回复哈~ 后来发现是pytorch版本较低，升级到1.12.0以上 则会包含CUDA_GCC_VERSIONS；但后续仍会报缺少libcublasLt.so.11的错误，推测是由于我的pytorch所需的cuda版本(11.6/11.7)和本机nvcc(11.1)不一致
另外想问下您当时安装编译时机器上nvcc version是多少呢，看您代码里依赖项是pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0，推测nvcc也是11.3吗

**Comment by MCZhi** [comment]
The version of nvcc on my machine is actually 11.1. But the code is running inside the conda environment.
