### ISSUE TITLE
Questions about how to submit the DIPP's prediction result on waymo prediction leaderboard?

### ISSUE THREAD

**Issue by ggosjw** [MCZhi/DIPP#18]
Hi, thank you for open-sourcing your great work.

I have a question regarding how to make a submission for the waymo motion prediction leaderboard using DIPP's prediction results.

Could you give me some intuitive suggestions?

I really appreciate any help you can provide.

**Comment by MCZhi** [comment]
Please refer to this [issue](https://github.com/waymo-research/waymo-open-dataset/issues/299). [This](https://github.com/waymo-research/waymo-open-dataset/issues/310) may be helpful too.

**Comment by ggosjw** [comment]
Thanks!

**Comment by creamcake233** [comment]
have you made  a submission for the waymo motion prediction leaderboard now?can i have one?
