### ISSUE TITLE
Simultaneous Training Problem

### ISSUE THREAD

**Issue by QingZhuanya** [MCZhi/DIPP#23]
Hello, thank you very much for your sharing. 
My question is that only a single graphics card can be used for training. Can multiple graphics cards be used for simultaneous training?

**Comment by MCZhi** [comment]
Hi, @QingZhuanya, thank you for reaching out. You can try using DDP with only the prediction model. However, while integrating it with the planner, it's worth noting that Theseus might not support multi-GPU training. This could potentially make joint training with multiple GPUs unfeasible.

**Comment by QingZhuanya** [comment]
@MCZhi okey,thanks.
There is another question, can the model rely on road information to give a reference line, as long as the reference line is a series of points in the center of the road?

**Comment by MCZhi** [comment]
Sure, that makes sense. We find the reference line as a series of waypoints on the road according to the ground truth trajectory in the code.

**Comment by QingZhuanya** [comment]
That is, do you take the gt as the reference line, and then input the reference line and the initial trajectory output of the model into the planning layer?



发自我的iPhone


------------------ Original ------------------
From: Zhiyu Huang ***@***.***&gt;
Date: Sat, Aug 26, 2023 2:36 AM
To: MCZhi/DIPP ***@***.***&gt;
Cc: qinying long ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [MCZhi/DIPP] Simultaneous Training Problem (Issue #23)





 
Sure, that makes sense. We find the reference line as a series of waypoints on the road according to the ground truth trajectory in the code.

**Comment by MCZhi** [comment]
Regarding the reference line, we do use the gt to find the nearest waypoints and use a cubic spline to interpolate the points and obtain the final reference line. The model (planner) takes the reference line and initial plan of the model as input.

**Comment by QingZhuanya** [comment]
thanks,I have a try. Thanks again for your sharing.
