### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError: corrupted_record at 0 [Op:IteratorGetNext]

### ISSUE THREAD

**Issue by WeiXiCZ** [MCZhi/DIPP#25]
Hi, @MCZhi!
Thank you very much for your nice work!
When I launch open loop test, it comes to the error as shown in the following figure
<img width="1129" alt="ed818cf58e69f9a0624772d9035be7f" src="https://github.com/MCZhi/DIPP/assets/86120782/346a716b-41d8-4f98-bfdf-4c0a5aae45dd">
Could you kindly help me to find the reason?
Thank you very much for your help!~

**Comment by MCZhi** [comment]
Hi, @WeiXiCZ, thank you for your interest. I guess that you didn't pass the correct argument `--test_set` to the program of open-loop testing. Please ensure that it is a directory containing some tfrecord files.

**Comment by WeiXiCZ** [comment]
Oh! excuse me, sorry to bother you!
I set --test_set as the directory containing the processed data, which is used for training actually. What a stupid mistake😅
Thank you again for your nice work and your help!
