### ISSUE TITLE
Is your work an agent-centered framework?

### ISSUE THREAD

**Issue by YangLinger** [MCZhi/DIPP#26]
In recent years, behavior prediction models have proliferated. In these models, choosing coordinate system to represent input and output can be roughly divided into two categories: Scene-centric and Agent-centric. Agent-centric models represent inputs and internal state in agent-centric coordinates, and perform inference reasoning in this frame3.(frame3 :Without loss of generality, an agent-centric frame transforms world coordinates so that the origin is set to the ego-agent’s center, and rotated so that the agent’s heading direction is the unit vector (x, y) = (1, 0). )The coordinates of road elements (e.g., lanes, crosswalks) and other agents’ states are described relative to the agent’s pose, thus the representation is inherently invariant to the global position and orientation of the agent. This can be considered a form of feature pre-processing that allows for models to specialize to an agent’s point of view, and in practice results in state-of-the-art performance on public benchmarks .Scene-centric models, on the other hand, do the bulk of world state encoding in a shared, fixed frame for all agents4(frame4:4Without loss of generality, this can be an arbitrary conceptual center of the scene elements.). Models that operate in this frame are typically “topdown” or “bird’s-eye-view” representations which discretize the world into spatial grid cells, and apply a convolutional neural net (CNN) backbone to encode the scene — although non-raster scene-centric approaches also exist .Now there are differences in our team. Some people think that your work is scene-centered, while others think that it is agent-centered, so I want to hear your opinion. What kind of work do you think is your work?

**Comment by MCZhi** [comment]
Hi, @YangLinger. I believe our work is categorized as a scene-centric approach, where all other agents' states and the attributes of vectorized map polylines are normalized based on the ego vehicle's state.

**Comment by YangLinger** [comment]
Thank you for your reply, which is a great help. I wish you a happy life and smooth work.
