### ISSUE TITLE
About score calculation

### ISSUE THREAD

**Issue by wangyy0** [MCZhi/DIPP#27]
Hi, thank you for sharing the great work!

While working on GameFormer, I noticed that you used a Gaussian distribution, which is not used in DIPP. Do you think adding Gaussian distribution will be more beneficial for trajectory scoring and subsequent training?

Bests.

**Comment by MCZhi** [comment]
Hi, @wangyy0. Sorry for the late reply. Yeah, I believe adding Gaussian distribution would be helpful in trajectory scoring but would not bring significant improvement. It may also make the training unstable somehow, so be careful with that.

**Comment by wangyy0** [comment]
thank you!
