### ISSUE TITLE
Total number of frames for training and testing

### ISSUE THREAD

**Issue by ggosjw** [MCZhi/DIPP#3]
**Thanks for open sourcing your amazing and wonderful work!** 
I have a question about the total number of frames for training:

I followed your Readme and downloaded the dataset only from uncompressed/scenario/training_20s. 
![image](https://user-images.githubusercontent.com/87901530/184566701-60ea5157-9424-41eb-983c-629824444b98.png)

Altogether 50 files:
![image](https://user-images.githubusercontent.com/87901530/184567079-e3a87321-1ede-4be6-b89b-7eef9a078804.png)

I followed your paper, splitting the dataset into 80% of training and 20%  of testing and validating. Then I run your data_process.py file to preprocess the data.

**However, when training, i found my total number of training frame is 36111, which is far fewer than 113,622 mentioned in your paper.**
![image](https://user-images.githubusercontent.com/87901530/184567272-942bb46e-5070-4e86-8194-40e8a938e1e5.png)
![image](https://user-images.githubusercontent.com/87901530/184567578-f3574766-24eb-4495-924a-034cc7d0ab34.png)
**So, my question is that whether i  download the incomplete dataset or there is something wrong in my reproduction process.**

**Thank you for your kind help and patience.**

**Comment by MCZhi** [comment]
Actually, there are 1000 files in the uncompressed/scenario/training 20s folder, so I suggest you go and check out the files on the website again. Note that I didn't use all the data files and only selected about 110 files in total.

**Comment by ggosjw** [comment]
OK,thank you for your kind help. That really helps me a lot.
