### ISSUE TITLE
Trajectory prediction of surrounding vehicles

### ISSUE THREAD

**Issue by 123yu456** [MCZhi/DIPP#30]
Hello, thank you for your great work. In your paper, you mainly predict the trajectory of the ego vehicle. How are the trajectories of other surrounding vehicles predicted? Is it generated based on historical inputs or other methods? I'm considering using your prediction model for lane change prediction and planning in highway scenarios, but I'm not sure if it's applicable, hence the questions. Thank you for your response.

**Comment by MCZhi** [comment]
Hi, @123yu456, thank you for your question. The neural network used in our method directly predicts the trajectories of other surrounding vehicles based on their historical inputs and map information, without the trajectory planning or refinement step as for the ego vehicle. This method could be useful for your research on highway lane change prediction. However, to improve prediction performance, you may need a more specific dataset that includes highway scenarios.

**Comment by 123yu456** [comment]
"Thank you for your response. Unfortunately, I haven't found a dataset that simultaneously includes highway data and vectorized maps. I found another paper of yours, 'Driving Behavior Modeling using Naturalistic Human Driving Data with Inverse Reinforcement Learning,' which might be more suitable for lane change prediction."
