### ISSUE TITLE
Training error: torch._C._LinAlgError: torch.linalg_cholesky

### ISSUE THREAD

**Issue by ydcttt** [MCZhi/DIPP#6]
Hi, this is excellent work. I try to reproduce it, but when training at Epoch 6/20, I got this error `torch._C._LinAlgError: torch.linalg_cholesky: (Batch element 11): The factorization could not be completed because the input is not positive-definite (the leading minor of order 48 is not positive-definite).` I want to ask how to solve it.
![image](https://user-images.githubusercontent.com/18325529/188772104-427359e8-142f-42a0-8157-43c465fca0f6.png)

**Comment by MCZhi** [comment]
Please see #1. This issue happens sometimes if using a dense solver, so I suggest using a sparse solver instead.
