### ISSUE TITLE
110 files from 1000 files from `training_20s`

### ISSUE THREAD

**Issue by jayabrata97** [MCZhi/DIPP#7]
@MCZhi, Thank you for publishing your work. I have a query: how do you choose 110 files from 1000 files in `training_20s`as discussed in https://github.com/MCZhi/DIPP/issues/3#issuecomment-1214697535? Also, can you please tell about which files are for training and which are for testing and validating? Currently, the data is in this format: `training_20s.tfrecord-00xxx-of01000`, where `xxx` is from `000` to `999`. Which `xxx` are used for training and which are for validation?

**Comment by MCZhi** [comment]
Thank you for your interest. They are selected randomly. I think using which files wouldn't make too much difference.

**Comment by jayabrata97** [comment]
Ok, thanks for the reply.

**Comment by jayabrata97** [comment]
@MCZhi, another question: Since `80%` of the dataset is for training, I assume that `88` files are for training. How many files should I give for the validation and testing directory? Or validation and testing is a single directory with `22` files?

**Comment by MCZhi** [comment]
Validation and testing files can be in a single directory with 22 files

**Comment by jayabrata97** [comment]
Ok, thank you.
