### ISSUE TITLE
Render and save video speed

### ISSUE THREAD

**Issue by yougeyxt** [MCZhi/DIPP#9]
Hi, I found the rendering and saving of videos are kinda slow (for example, it takes more than 10 minutes to save a 15 seconds visualization video), is that normal? Any comments are appreciated. Thank you.

**Comment by MCZhi** [comment]
The process of rendering and saving videos on my machine is kinda slow too. Presumably, I think it is the problem of matplotlib and you may try other libraries to convert the stored images to videos, which could speed up the process.

**Comment by yougeyxt** [comment]
Thanks for the comment and suggestion!
